# Generated by Django 4.2.20 on 2025-05-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cargo", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="LocalizacaoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("endereco", models.CharField(max_length=250, verbose_name="endereço")),
                ("capacidadeMaxima", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cpf", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=250, verbose_name="endereço")),
            ],
        ),
        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Orcamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valorPrevisto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valorReal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("despesas", models.TextField()),
                ("concluido", models.BooleanField(default=False)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.tipoevento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("dataEvento", models.DateTimeField(auto_now_add=True)),
                (
                    "descricao",
                    models.CharField(max_length=250, verbose_name="descrição"),
                ),
                (
                    "tipoEvento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="paginas.tipoevento",
                    ),
                ),
            ],
        ),
    ]
