# Generated by Django 4.2.20 on 2025-09-01 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0002_evento_cadastrado_por"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evento",
            options={"ordering": ["-cadastrado_por"]},
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={"ordering": ["nome", "cargo"]},
        ),
        migrations.AlterModelOptions(
            name="localizacaoevento",
            options={"ordering": ["endereco"]},
        ),
        migrations.AlterModelOptions(
            name="orcamento",
            options={"ordering": ["valor_real"]},
        ),
        migrations.AlterModelOptions(
            name="perfil",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="tipoevento",
            options={"ordering": ["nome"]},
        ),
    ]
